dist: trusty
language: r
sudo: false
r: 3.6.1   



cache:
  # Main R library
  packages: true
  
  directories:
    
    - travis_phantomjs

apt_packages:  

  - libgdal-dev   
  
  - libudunits2-dev   
  
r_packages:

  - rsconnect  

  - shiny   

  - tidyverse  

  - kableExtra   
  
  - rmarkdown   
  
  - kernlab     
  
  - ggplot2       
  
  - lattice     
  
  - caret  
  
  - plotROC  
  
  - shinythemes  
 
  - plotly   
  
  - shinythemes   
  
  - xlsx  
  
  - dplyr  
  
  - lubridate  
  
  - tidyr  
  
  - stringr  
  
  

script:

  - server.R  
  
  - ui.R
