dist: trusty
sudo: false
latex: true
language: r
r: 3.6.1
warnings_are_errors: false
cache:
  packages: true
apt_packages:
  - libgdal-dev
  - libudunits2-dev
r_packages:
  - rsconnect
  - shiny
  - tidyverse
  - rmarkdown
  - kernlab 
  - xlsx
  - ggplot2
  - lattice
  - shinythemes 
script:
  - r -f deploy.R
