dist: trusty
sudo: false
latex: true
language: r
r: 3.6.1
warnings_are_errors: false
cache:
  packages: true
apt_packages:
  - libgdal-dev
  - libudunits2-dev
r_packages:
  - rsconnect
  - shiny 
  - littler
script:
  - R -f deploy.R
