dist: xenial
language: r
sudo: false
r: release    

warnings_are_error: false

cache:
  packages: true 
  
r_packages:

  - rsconnect  

  - shiny   

  - tidyverse  

  - kableExtra   
  
  - rmarkdown   
  
  - kernlab     
  
  - ggplot2       
  
  - lattice     
  
  - caret  
  
  - plotROC  
  
  - shinythemes  
 
  - plotly   
  
  - shinythemes   
  
  - xlsx  
  
  - dplyr  
  
  - lubridate  
  
  - tidyr  
  
  - stringr  
  
  

script:

  - R -f deploy.R
