
language: r

dist: xenial

sudo: false

latex: true

r: release

warnings_are_errors: false

cache:

  packages: true

apt_packages:  

  - libgdal-dev   
  
  - libudunits2-dev   
  
r_packages:

  - rsconnect  

  - shiny   

  - tidyverse  

  - kableExtra   
  
  - rmarkdown   
  
  - kernlab     
  
  - ggplot2       
  
  - lattice     
  
  - caret  
  
  - plotROC  
  
  - shinythemes  
 
  - plotly   
  
  - shinythemes   
  
  - xlsx  
  
  - dplyr  
  
  - lubridate  
  
  - tidyr  
  
  - stringr  
  
  

script:

  - R -f deploy.R   
  
  - server.R  
  
  - ui.R
